<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sai-PC" name="On chrome" tests="4" failures="3" timestamp="7 Oct 2016 02:26:33 GMT" time="16.715" errors="0">
  <testcase name="loginTest" time="16.614" classname="day21.Login"/>
  <testcase name="addEmployeeTest" time="0.002" classname="day21.AddEmployee">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at day21.AddEmployee.addEmployeeTest(AddEmployee.java:10)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase name="deleteEmpTest" time="0.001" classname="day21.DeleteEmployee">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at day21.DeleteEmployee.deleteEmpTest(DeleteEmployee.java:13)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- deleteEmpTest -->
  <testcase name="logoutTest" time="0.001" classname="day21.Logout">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at day21.Logout.logoutTest(Logout.java:10)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- On chrome -->
